# Generated by Django 6.0.7 on 2026-07-23 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_matriculeconfig_include_initials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matriculeconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='matriculeconfig',
            name='include_year',
            field=models.BooleanField(default=True, verbose_name="Inclure l'année en cours"),
        ),
        migrations.AlterField(
            model_name='matriculeconfig',
            name='num_digits',
            field=models.PositiveSmallIntegerField(default=4, help_text='Ex. 4 → 0001, 0002 …', verbose_name='Nombre de chiffres du numéro séquentiel'),
        ),
        migrations.AlterField(
            model_name='matriculeconfig',
            name='prefix',
            field=models.CharField(blank=True, default='', help_text='Laissez vide pour ne pas utiliser de préfixe.', max_length=10, verbose_name='Préfixe (ex. ELV, 22)'),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
