# Generated by Django 6.0.7 on 2026-07-23 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_initial'),
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working_days', models.JSONField(default=list, help_text='Indices des jours travaillés (0=Lundi, 5=Samedi)', verbose_name='Jours de cours')),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_config', to='schools.school')),
            ],
            options={
                'verbose_name': 'Configuration emploi du temps',
            },
        ),
    ]
