"""Student forms — V1.4: matricule (student_id) is auto-generated, shown read-only on edit."""

from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Row, Column, Submit, Fieldset
from .models import Student


class StudentForm(forms.ModelForm):
    """Create or edit a student.

    V1.4 behaviour:
    - On creation (no instance.pk): student_id is excluded — it will be
      auto-generated by Student.save().
    - On edit (instance.pk set): student_id is shown as a disabled read-only
      field so users can see the matricule but cannot change it.
    """

    class Meta:
        model = Student
        fields = [
            'student_id', 'first_name', 'last_name', 'gender',
            'date_of_birth', 'place_of_birth', 'nationality',
            'address', 'phone', 'email', 'photo',
            'previous_school', 'medical_notes',
        ]
        widgets = {
            'date_of_birth': forms.DateInput(attrs={'type': 'date'}),
            'address': forms.Textarea(attrs={'rows': 2}),
            'medical_notes': forms.Textarea(attrs={'rows': 2}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        if self.instance and self.instance.pk:
            # Editing an existing student: show matricule as read-only.
            self.fields['student_id'].disabled = True
            self.fields['student_id'].help_text = (
                "Le matricule est attribué automatiquement et ne peut pas être modifié."
            )
            identity_fields = Fieldset('Identité',
                Row(Column('student_id', css_class='col-md-4'), Column('gender', css_class='col-md-4')),
                Row(Column('first_name'), Column('last_name')),
                Row(Column('date_of_birth'), Column('place_of_birth')),
                'nationality',
                'photo',
            )
        else:
            # Creating a new student: hide student_id — auto-generated by model.
            self.fields.pop('student_id')
            identity_fields = Fieldset('Identité',
                Row(Column('first_name'), Column('last_name')),
                Row(Column('gender'), Column('date_of_birth')),
                Row(Column('place_of_birth'), Column('nationality')),
                'photo',
            )

        self.helper = FormHelper()
        self.helper.layout = Layout(
            identity_fields,
            Fieldset('Coordonnées',
                'address',
                Row(Column('phone'), Column('email')),
            ),
            Fieldset('Informations scolaires',
                'previous_school',
                'medical_notes',
            ),
            Submit('submit', 'Enregistrer', css_class='btn btn-primary mt-3'),
        )
